# Generated by Django 5.2.7 on 2025-12-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("architecture", models.CharField(max_length=50)),
                ("accuracy", models.FloatField()),
                ("auc_score", models.FloatField()),
                ("sensitivity", models.FloatField()),
                ("specificity", models.FloatField()),
                ("trained_on", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("model_path", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_id",
                    models.CharField(
                        blank=True, editable=False, max_length=30, unique=True
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("doctor_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detection_id",
                    models.CharField(
                        blank=True, editable=False, max_length=30, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_file", models.FileField(upload_to="mri_uploads/%Y/%m/%d/")),
                ("file_size", models.IntegerField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "predicted_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("prediction_probability", models.JSONField(blank=True, null=True)),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("analysis_details", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("patient_age", models.IntegerField(blank=True, null=True)),
                (
                    "patient_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("clinician_notes", models.TextField(blank=True, null=True)),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="detection.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FHIRDiagnosticReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        blank=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "fhir_resource_type",
                    models.CharField(default="DiagnosticReport", max_length=50),
                ),
                ("fhir_version", models.CharField(default="4.0.1", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("partial", "Partial"),
                            ("preliminary", "Preliminary"),
                            ("final", "Final"),
                            ("amended", "Amended"),
                            ("corrected", "Corrected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="final",
                        max_length=20,
                    ),
                ),
                ("category", models.JSONField(default=dict)),
                ("code", models.JSONField(default=dict)),
                ("subject", models.JSONField(default=dict)),
                ("encounter", models.JSONField(blank=True, null=True)),
                ("effective_datetime", models.DateTimeField()),
                ("issued", models.DateTimeField(auto_now_add=True)),
                ("performer", models.JSONField(default=list)),
                ("result", models.JSONField(default=list)),
                ("imaging_study", models.JSONField(blank=True, null=True)),
                ("media", models.JSONField(default=list)),
                ("conclusion", models.TextField()),
                ("conclusion_code", models.JSONField(default=list)),
                ("presented_form", models.JSONField(default=list)),
                (
                    "hospital_system_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hospital_name", models.CharField(max_length=200)),
                ("department", models.CharField(default="Neurology", max_length=100)),
                ("fhir_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "detection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fhir_report",
                        to="detection.detectionresult",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fhir_reports_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fhir_reports_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="detection_a_patient_07e2fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="detection_a_doctor__1c5503_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date"], name="detection_a_appoint_31dce9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionresult",
            index=models.Index(
                fields=["patient", "-created_at"], name="detection_d_patient_e77bd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionresult",
            index=models.Index(
                fields=["doctor", "-created_at"], name="detection_d_doctor__5b1ded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionresult",
            index=models.Index(
                fields=["appointment"], name="detection_d_appoint_ba9ef7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionresult",
            index=models.Index(fields=["status"], name="detection_d_status_a29dd6_idx"),
        ),
        migrations.AddIndex(
            model_name="fhirdiagnosticreport",
            index=models.Index(
                fields=["report_id"], name="detection_f_report__5b29f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fhirdiagnosticreport",
            index=models.Index(
                fields=["patient", "-issued"], name="detection_f_patient_ec3027_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fhirdiagnosticreport",
            index=models.Index(
                fields=["doctor", "-issued"], name="detection_f_doctor__aaae5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fhirdiagnosticreport",
            index=models.Index(fields=["status"], name="detection_f_status_07b20e_idx"),
        ),
    ]
