# Generated by Django 5.2.7 on 2026-04-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_normalize_predicted_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='predicted_class',
            field=models.CharField(blank=True, choices=[('alzheimers', "Alzheimer's Disease"), ('cn', 'Control/Normal')], max_length=50, null=True),
        ),
    ]
