# Generated by Django 5.2.7 on 2026-04-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_add_subtype_classifier_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='preprocessed_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
