# Generated by Django 5.2.7 on 2026-04-12 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_detectionresult_preprocessed_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='predicted_class',
            field=models.CharField(blank=True, choices=[('alzheimers', "Alzheimer's Disease"), ('dementia', 'Dementia Detected'), ('cn', 'Control/Normal'), ('pd', "Parkinson's Disease"), ('ftd', 'Frontotemporal Dementia')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_accepted', models.BooleanField(default=True)),
                ('doctor_conclusion', models.TextField(help_text="Doctor's own clinical conclusion (visible to patient when sent)")),
                ('doctor_notes', models.TextField(blank=True, help_text='Internal notes visible only to the doctor — NOT sent to the patient')),
                ('patient_summary', models.TextField(help_text='Plain-language message the patient will see')),
                ('is_sent_to_patient', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='detection.detectionresult')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_reviews', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='detection_d_patient_3810fb_idx'), models.Index(fields=['doctor', '-created_at'], name='detection_d_doctor__e11e90_idx'), models.Index(fields=['is_sent_to_patient'], name='detection_d_is_sent_59811b_idx')],
            },
        ),
    ]
