# Generated by Django 5.2.7 on 2026-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0006_alter_detectionresult_predicted_class_doctorreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorreview",
            name="doctor_override_class",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If AI is overridden, the doctor-selected diagnosis class",
                max_length=50,
            ),
        ),
    ]
