# Generated by Django 5.2.7 on 2026-03-30 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Canonical form of the patient's question."
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        help_text="The consistent answer to give every time."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("orientation", "Orientation"),
                            ("family", "Family"),
                            ("routine", "Routine"),
                            ("identity", "Identity"),
                            ("safety", "Safety"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("ask_count", models.PositiveIntegerField(default=1)),
                ("last_asked", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_faqs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ask_count", "-last_asked"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-ask_count"],
                        name="companion_p_patient_7d8d51_idx",
                    )
                ],
            },
        ),
    ]
