# Generated by Django 5.2.7 on 2026-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companion", "0002_patientfaq"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientfaq",
            name="question_embedding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
