# Generated by Django 5.2.7 on 2026-04-01 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companion", "0003_add_faq_question_embedding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lifestoryentry",
            options={"ordering": ["-priority", "-created_at"]},
        ),
        migrations.AddField(
            model_name="lifestoryentry",
            name="audio_file",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="lifestoryentry",
            name="audio_transcript",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lifestoryentry",
            name="entry_type",
            field=models.CharField(
                choices=[("text", "Text Entry"), ("voice", "Voice Message")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lifestoryentry",
            name="priority",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lifestoryentry",
            name="trigger_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Questions that should trigger this entry's answer",
            ),
        ),
        migrations.AlterField(
            model_name="lifestoryentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("family", "Family & Relationships"),
                    ("daily_routine", "Daily Routine & Care"),
                    ("favorites", "Favorites & Preferences"),
                    ("memories", "Important Memories"),
                    ("places", "Places & Home"),
                    ("health", "Health Information"),
                    ("people", "Important People"),
                    ("instructions", "Care Instructions"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lifestoryentry",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="lifestoryentry",
            index=models.Index(
                fields=["patient", "entry_type"], name="companion_l_patient_5ed298_idx"
            ),
        ),
    ]
